name: international_phone_input
description: International Phone Number Input For Flutter. This packages validates phone number input value using the libphonenumber package.
version: 1.0.4
homepage: https://github.com/niinyarko/flutter-international-phone-input

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    libphonenumber: ^1.0.0

dev_dependencies:
    test: ^1.6.0
    flutter_test:
        sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    uses-material-design: true

    assets:
        - assets/countries.json
        - assets/flags/tg.png
        - assets/flags/me.png
        - assets/flags/la.png
        - assets/flags/mr.png
        - assets/flags/ni.png
        - assets/flags/lv.png
        - assets/flags/om.png
        - assets/flags/af.png
        - assets/flags/cy.png
        - assets/flags/bj.png
        - assets/flags/aq.png
        - assets/flags/cn.png
        - assets/flags/gb-sct.png
        - assets/flags/co.png
        - assets/flags/cx.png
        - assets/flags/ag.png
        - assets/flags/ms.png
        - assets/flags/md.png
        - assets/flags/zm.png
        - assets/flags/vn.png
        - assets/flags/tf.png
        - assets/flags/td.png
        - assets/flags/yt.png
        - assets/flags/lb.png
        - assets/flags/mf.png
        - assets/flags/lu.png
        - assets/flags/mq.png
        - assets/flags/cz.png
        - assets/flags/ae.png
        - assets/flags/cm.png
        - assets/flags/bi.png
        - assets/flags/ar.png
        - assets/flags/as.png
        - assets/flags/bh.png
        - assets/flags/cl.png
        - assets/flags/ad.png
        - assets/flags/mp.png
        - assets/flags/lt.png
        - assets/flags/mg.png
        - assets/flags/lc.png
        - assets/flags/tr.png
        - assets/flags/ua.png
        - assets/flags/tv.png
        - assets/flags/vi.png
        - assets/flags/mt.png
        - assets/flags/no.png
        - assets/flags/mc.png
        - assets/flags/ch.png
        - assets/flags/bl.png
        - assets/flags/aw.png
        - assets/flags/bz.png
        - assets/flags/bm.png
        - assets/flags/ci.png
        - assets/flags/mu.png
        - assets/flags/us.png
        - assets/flags/tw.png
        - assets/flags/ye.png
        - assets/flags/mw.png
        - assets/flags/nl.png
        - assets/flags/ls.png
        - assets/flags/bo.png
        - assets/flags/at.png
        - assets/flags/ck.png
        - assets/flags/by.png
        - assets/flags/au.png
        - assets/flags/bn.png
        - assets/flags/ma.png
        - assets/flags/nz.png
        - assets/flags/lr.png
        - assets/flags/mv.png
        - assets/flags/tc.png
        - assets/flags/ug.png
        - assets/flags/tt.png
        - assets/flags/pl.png
        - assets/flags/rs.png
        - assets/flags/in.png
        - assets/flags/ge.png
        - assets/flags/gr.png
        - assets/flags/gs.png
        - assets/flags/gd.png
        - assets/flags/io.png
        - assets/flags/hk.png
        - assets/flags/kp.png
        - assets/flags/gb-nir.png
        - assets/flags/kg.png
        - assets/flags/pm.png
        - assets/flags/sv.png
        - assets/flags/re.png
        - assets/flags/sa.png
        - assets/flags/sc.png
        - assets/flags/st.png
        - assets/flags/ke.png
        - assets/flags/im.png
        - assets/flags/kr.png
        - assets/flags/gf.png
        - assets/flags/dj.png
        - assets/flags/gq.png
        - assets/flags/gp.png
        - assets/flags/dk.png
        - assets/flags/gg.png
        - assets/flags/il.png
        - assets/flags/pn.png
        - assets/flags/sb.png
        - assets/flags/py.png
        - assets/flags/ru.png
        - assets/flags/kw.png
        - assets/flags/do.png
        - assets/flags/gt.png
        - assets/flags/gb.png
        - assets/flags/gu.png
        - assets/flags/je.png
        - assets/flags/hm.png
        - assets/flags/sg.png
        - assets/flags/pk.png
        - assets/flags/sr.png
        - assets/flags/se.png
        - assets/flags/jp.png
        - assets/flags/gw.png
        - assets/flags/eh.png
        - assets/flags/dz.png
        - assets/flags/ga.png
        - assets/flags/fr.png
        - assets/flags/dm.png
        - assets/flags/hn.png
        - assets/flags/sd.png
        - assets/flags/rw.png
        - assets/flags/ph.png
        - assets/flags/ss.png
        - assets/flags/qa.png
        - assets/flags/pe.png
        - assets/flags/pr.png
        - assets/flags/si.png
        - assets/flags/ht.png
        - assets/flags/es.png
        - assets/flags/gl.png
        - assets/flags/gm.png
        - assets/flags/er.png
        - assets/flags/fi.png
        - assets/flags/ee.png
        - assets/flags/kn.png
        - assets/flags/hu.png
        - assets/flags/iq.png
        - assets/flags/ky.png
        - assets/flags/sh.png
        - assets/flags/ps.png
        - assets/flags/pf.png
        - assets/flags/sj.png
        - assets/flags/id.png
        - assets/flags/is.png
        - assets/flags/eg.png
        - assets/flags/fk.png
        - assets/flags/fj.png
        - assets/flags/gn.png
        - assets/flags/gy.png
        - assets/flags/ir.png
        - assets/flags/km.png
        - assets/flags/ie.png
        - assets/flags/kz.png
        - assets/flags/ro.png
        - assets/flags/sk.png
        - assets/flags/pg.png
        - assets/flags/pt.png
        - assets/flags/so.png
        - assets/flags/sx.png
        - assets/flags/hr.png
        - assets/flags/ki.png
        - assets/flags/jm.png
        - assets/flags/eu.png
        - assets/flags/ec.png
        - assets/flags/et.png
        - assets/flags/fo.png
        - assets/flags/kh.png
        - assets/flags/sy.png
        - assets/flags/sn.png
        - assets/flags/pw.png
        - assets/flags/sl.png
        - assets/flags/gb-eng.png
        - assets/flags/fm.png
        - assets/flags/gi.png
        - assets/flags/de.png
        - assets/flags/gh.png
        - assets/flags/jo.png
        - assets/flags/it.png
        - assets/flags/pa.png
        - assets/flags/sz.png
        - assets/flags/sm.png
        - assets/flags/tn.png
        - assets/flags/ml.png
        - assets/flags/cg.png
        - assets/flags/ax.png
        - assets/flags/ao.png
        - assets/flags/bt.png
        - assets/flags/bb.png
        - assets/flags/cf.png
        - assets/flags/mm.png
        - assets/flags/li.png
        - assets/flags/na.png
        - assets/flags/mz.png
        - assets/flags/to.png
        - assets/flags/vg.png
        - assets/flags/ve.png
        - assets/flags/tz.png
        - assets/flags/tm.png
        - assets/flags/mx.png
        - assets/flags/nc.png
        - assets/flags/mo.png
        - assets/flags/lk.png
        - assets/flags/cd.png
        - assets/flags/al.png
        - assets/flags/bw.png
        - assets/flags/cr.png
        - assets/flags/bv.png
        - assets/flags/am.png
        - assets/flags/az.png
        - assets/flags/ba.png
        - assets/flags/mn.png
        - assets/flags/nu.png
        - assets/flags/my.png
        - assets/flags/tl.png
        - assets/flags/ws.png
        - assets/flags/th.png
        - assets/flags/xk.png
        - assets/flags/nf.png
        - assets/flags/ly.png
        - assets/flags/ai.png
        - assets/flags/br.png
        - assets/flags/cv.png
        - assets/flags/be.png
        - assets/flags/ca.png
        - assets/flags/bd.png
        - assets/flags/cw.png
        - assets/flags/bs.png
        - assets/flags/ng.png
        - assets/flags/mk.png
        - assets/flags/np.png
        - assets/flags/va.png
        - assets/flags/uz.png
        - assets/flags/um.png
        - assets/flags/tk.png
        - assets/flags/vc.png
        - assets/flags/zw.png
        - assets/flags/nr.png
        - assets/flags/ne.png
        - assets/flags/cu.png
        - assets/flags/bq.png
        - assets/flags/bf.png
        - assets/flags/bg.png
        - assets/flags/cc.png
        - assets/flags/gb-wls.png
        - assets/flags/mh.png
        - assets/flags/za.png
        - assets/flags/uy.png
        - assets/flags/wf.png
        - assets/flags/vu.png
        - assets/flags/tj.png
        - assets/flags/an.png
